"""add gst components to quote

Revision ID: 08ee8654d738
Revises: 9d9620a6245d
Create Date: 2026-02-14 20:18:34.163001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee8654d738'
down_revision = '9d9620a6245d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_quote_items_service_id'), ['service_id'], unique=False)
        batch_op.create_foreign_key(None, 'lead_services', ['service_id'], ['id'])

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('igst')
        batch_op.drop_column('sgst')
        batch_op.drop_column('cgst')

    with op.batch_alter_table('quote_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quote_items_service_id'))
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
