"""approval steps + quote approvals step-level

Revision ID: 0d16f64a1e36
Revises: 26cb1e4ae225
Create Date: 2026-01-26 10:48:02.144726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d16f64a1e36'
down_revision = '26cb1e4ae225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rule_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['approval_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_step_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('step_order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('approver_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approver_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['approver_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'approval_rule_steps', ['rule_step_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('remark',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('approver_user_id')
        batch_op.drop_column('approver_role')
        batch_op.drop_column('step_order')
        batch_op.drop_column('rule_step_id')

    op.drop_table('approval_rule_steps')
    # ### end Alembic commands ###
