"""Invoice and PI

Revision ID: 3c4109ddaba5
Revises: 80d51c1bd37e
Create Date: 2026-02-14 22:46:59.017770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4109ddaba5'
down_revision = '80d51c1bd37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proforma_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pi_no', sa.String(length=40), nullable=False),
    sa.Column('pi_date', sa.Date(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_branch_id', sa.Integer(), nullable=True),
    sa.Column('company_branch_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_branch_id'], ['client_branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_branch_id'], ['company_branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_invoices_client_branch_id'), ['client_branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_company_branch_id'), ['company_branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_pi_no'), ['pi_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_proforma_invoices_quote_id'), ['quote_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=40), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_branch_id', sa.Integer(), nullable=True),
    sa.Column('company_branch_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_branch_id'], ['client_branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_branch_id'], ['company_branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pi_id'], ['proforma_invoices.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_branch_id'), ['client_branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_company_branch_id'), ['company_branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_pi_id'), ['pi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_quote_id'), ['quote_id'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transfer_type', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('finance_remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_quote_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_pi_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoices_company_branch_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_branch_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('proforma_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_quote_id'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_pi_no'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_company_branch_id'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_client_id'))
        batch_op.drop_index(batch_op.f('ix_proforma_invoices_client_branch_id'))

    op.drop_table('proforma_invoices')
    # ### end Alembic commands ###
