"""add margin settings

Revision ID: 5bd48f1e9204
Revises: dfa7e60abfc2
Create Date: 2026-02-16 17:28:39.513351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd48f1e9204'
down_revision = 'dfa7e60abfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('margin_settings')
    # ### end Alembic commands ###
