"""Invoice Permission

Revision ID: 63aadd810c2b
Revises: dc1848190dda
Create Date: 2026-02-15 22:08:51.205586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aadd810c2b'
down_revision = 'dc1848190dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_request_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('invoice_request_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invoice_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_generated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['invoice_requested_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['invoice_generated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_generated_by_id')
        batch_op.drop_column('invoice_generated_at')
        batch_op.drop_column('invoice_request_status')
        batch_op.drop_column('invoice_request_note')
        batch_op.drop_column('invoice_requested_by_id')
        batch_op.drop_column('invoice_requested_at')

    # ### end Alembic commands ###
