"""add due_date and credit_days to invoices

Revision ID: 646ddbaae923
Revises: ad0c145db4e2
Create Date: 2026-02-16 17:00:39.133314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646ddbaae923'
down_revision = 'ad0c145db4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_due_date'))
        batch_op.drop_column('due_date')
        batch_op.drop_column('credit_days')

    # ### end Alembic commands ###
