"""add gst components to quote 2

Revision ID: 80d51c1bd37e
Revises: 08ee8654d738
Create Date: 2026-02-14 20:37:44.271448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d51c1bd37e'
down_revision = '08ee8654d738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company_branches', ['company_branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_branch_id')

    with op.batch_alter_table('company_branches', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
