"""user master: auth_provider + external ids + designations + employee profile

Revision ID: 8d15669bdff3
Revises: 0d16f64a1e36
Create Date: 2026-01-26 12:41:29.768811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d15669bdff3'
down_revision = '0d16f64a1e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_designation_id', sa.String(length=120), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designations_external_designation_id'), ['external_designation_id'], unique=False)

    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('reporting_manager_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_profiles_employee_code'), ['employee_code'], unique=True)

    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.alter_column('approver_role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('external_user_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_user_id'), ['external_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('external_user_id')
        batch_op.drop_column('auth_provider')

    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.alter_column('approver_role',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_profiles_employee_code'))

    op.drop_table('employee_profiles')
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designations_external_designation_id'))

    op.drop_table('designations')
    # ### end Alembic commands ###
