"""add phone_country to leads

Revision ID: 9d0a2c29d6d8
Revises: f92a148a12fb
Create Date: 2026-02-09 12:37:36.046354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d0a2c29d6d8'
down_revision = 'f92a148a12fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_country', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('industry_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_industry_id'), ['industry_id'], unique=False)
        batch_op.create_foreign_key(None, 'industries', ['industry_id'], ['id'])
        batch_op.drop_column('industry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_industry_id'))
        batch_op.drop_column('industry_id')
        batch_op.drop_column('phone_country')

    op.drop_table('industries')
    # ### end Alembic commands ###
