"""CLuster 

Revision ID: 9e9be5827d39
Revises: 5bd48f1e9204
Create Date: 2026-02-16 18:43:44.521565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9be5827d39'
down_revision = '5bd48f1e9204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('head_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_head_user_id'), ['head_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_head_user_id'))

    op.drop_table('clusters')
    # ### end Alembic commands ###
