"""add monthly_ctc update

Revision ID: ad0c145db4e2
Revises: 0eed2e3e9bda
Create Date: 2026-02-16 16:48:27.167975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad0c145db4e2'
down_revision = '0eed2e3e9bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_profiles_monthly_ctc'))
        batch_op.drop_column('monthly_ctc')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_ctc', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_monthly_ctc'), ['monthly_ctc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_monthly_ctc'))
        batch_op.drop_column('monthly_ctc')

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_ctc', mysql.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_profiles_monthly_ctc'), ['monthly_ctc'], unique=False)

    # ### end Alembic commands ###
