"""Add estimated closure and final payment dates

Revision ID: b3158a09f042
Revises: a88296a94c4c
Create Date: 2026-02-03 16:35:55.433644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3158a09f042'
down_revision = 'a88296a94c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_closure_date', sa.Date(), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_closure_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('final_payment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('final_payment_date')
        batch_op.drop_column('estimated_closure_date')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('estimated_closure_date')

    # ### end Alembic commands ###
