"""GST Field before client conversion

Revision ID: c4c1770d59f7
Revises: 3c4109ddaba5
Create Date: 2026-02-14 23:14:07.412778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c1770d59f7'
down_revision = '3c4109ddaba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_gstin', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_gst_applicable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('is_gst_applicable')
        batch_op.drop_column('billing_gstin')
        batch_op.drop_column('billing_state')

    # ### end Alembic commands ###
