"""client industry fk

Revision ID: d464e64d1f78
Revises: 58738e1425f2
Create Date: 2026-02-09 14:55:28.720821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd464e64d1f78'
down_revision = '58738e1425f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_industry_id'), ['industry_id'], unique=False)
        batch_op.create_foreign_key(None, 'industries', ['industry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_clients_industry_id'))
        batch_op.drop_column('industry_id')

    # ### end Alembic commands ###
