"""Proposal sent Button

Revision ID: dbfc64fb7442
Revises: d464e64d1f78
Create Date: 2026-02-09 15:44:59.376469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfc64fb7442'
down_revision = 'd464e64d1f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=200), nullable=False),
    sa.Column('branch_address', sa.Text(), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'branch_name', name='uq_company_branch_name')
    )
    with op.batch_alter_table('company_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_branches_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proposal_confirmed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['proposal_confirmed_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_company_branch_id'), ['company_branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'company_branches', ['company_branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_company_branch_id'))
        batch_op.drop_column('company_branch_id')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposal_confirmed_by_id')
        batch_op.drop_column('proposal_confirmed_at')

    with op.batch_alter_table('company_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_branches_company_id'))

    op.drop_table('company_branches')
    op.drop_table('companies')
    # ### end Alembic commands ###
