"""pi request workflow fields

Revision ID: dc1848190dda
Revises: c4c1770d59f7
Create Date: 2026-02-15 20:55:31.448832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1848190dda'
down_revision = 'c4c1770d59f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pi_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pi_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pi_request_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pi_request_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pi_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pi_generated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['pi_requested_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['pi_generated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pi_generated_by_id')
        batch_op.drop_column('pi_generated_at')
        batch_op.drop_column('pi_request_status')
        batch_op.drop_column('pi_request_note')
        batch_op.drop_column('pi_requested_by_id')
        batch_op.drop_column('pi_requested_at')

    # ### end Alembic commands ###
