"""add projects margin tracking

Revision ID: dfa7e60abfc2
Revises: 646ddbaae923
Create Date: 2026-02-16 17:23:20.823791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa7e60abfc2'
down_revision = '646ddbaae923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('account_manager_user_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('margin_flag', sa.Boolean(), nullable=True),
    sa.Column('margin_reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_manager_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['client_branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_account_manager_user_id'), ['account_manager_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_quote_id'), ['quote_id'], unique=False)

    op.create_table('project_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('cost_head', sa.String(length=120), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_costs_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_costs_project_id'))

    op.drop_table('project_costs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_quote_id'))
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_index(batch_op.f('ix_projects_client_id'))
        batch_op.drop_index(batch_op.f('ix_projects_branch_id'))
        batch_op.drop_index(batch_op.f('ix_projects_account_manager_user_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
