"""Fix client_document foreign keys

Revision ID: f92a148a12fb
Revises: b3158a09f042
Create Date: 2026-02-03 18:24:01.859392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92a148a12fb'
down_revision = 'b3158a09f042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_documents_quote_id'), ['quote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_documents_quote_id'))
        batch_op.drop_index(batch_op.f('ix_client_documents_client_id'))

    op.drop_table('client_documents')
    # ### end Alembic commands ###
