"""add monthly_ctc to users

Revision ID: fa3116f02e8c
Revises: 5082691e7862
Create Date: 2026-02-16 16:09:21.247803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3116f02e8c'
down_revision = '5082691e7862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_ctc', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_monthly_ctc'), ['monthly_ctc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_monthly_ctc'))
        batch_op.drop_column('monthly_ctc')

    # ### end Alembic commands ###
