"""Add clients, branches, contacts; link to leads/opps/quotes

Revision ID: fda51f0adbc1
Revises: 8d15669bdff3
Create Date: 2026-02-02 19:13:43.321738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda51f0adbc1'
down_revision = '8d15669bdff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_industry', sa.String(length=120), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('client_type', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('client_category', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_client_id', sa.String(length=120), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_external_client_id'), ['external_client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_pan'), ['pan'], unique=False)

    op.create_table('client_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('branch_location', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=20), nullable=True),
    sa.Column('gst', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'branch_location', name='uq_client_branch_location')
    )
    with op.batch_alter_table('client_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_branches_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_branches_gst'), ['gst'], unique=False)

    op.create_table('branch_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['client_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_contacts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_contacts_email'), ['email'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key(None, 'client_branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_opportunities_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_branches', ['branch_id'], ['id'])

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quotes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_client_id'), ['client_id'], unique=False)
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'client_branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quotes_client_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_branch_id'))
        batch_op.drop_column('branch_id')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_opportunities_client_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_branch_id'))
        batch_op.drop_column('branch_id')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_client_id'))
        batch_op.drop_index(batch_op.f('ix_leads_branch_id'))
        batch_op.drop_column('branch_id')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('branch_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_branch_contacts_branch_id'))

    op.drop_table('branch_contacts')
    with op.batch_alter_table('client_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_branches_gst'))
        batch_op.drop_index(batch_op.f('ix_client_branches_client_id'))

    op.drop_table('client_branches')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_pan'))
        batch_op.drop_index(batch_op.f('ix_clients_external_client_id'))
        batch_op.drop_index(batch_op.f('ix_clients_company_name'))

    op.drop_table('clients')
    # ### end Alembic commands ###
